name: vtk_flutter_example
description: Demonstrates generic typed VTK pipelines with vtk_flutter.
publish_to: none

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  vtk_flutter:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
