// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Generated bindings for the vtk_flutter native ABI.
class VtkFlutterBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VtkFlutterBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VtkFlutterBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int vtk_flutter_abi_version() {
    return _vtk_flutter_abi_version();
  }

  late final _vtk_flutter_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function()>>(
        'vtk_flutter_abi_version',
      );
  late final _vtk_flutter_abi_version = _vtk_flutter_abi_versionPtr
      .asFunction<int Function()>();

  void vtk_flutter_status_clear(ffi.Pointer<VtkFlutterStatus> status) {
    return _vtk_flutter_status_clear(status);
  }

  late final _vtk_flutter_status_clearPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VtkFlutterStatus>)>
      >('vtk_flutter_status_clear');
  late final _vtk_flutter_status_clear = _vtk_flutter_status_clearPtr
      .asFunction<void Function(ffi.Pointer<VtkFlutterStatus>)>();

  int vtk_flutter_session_create(
    ffi.Pointer<ffi.Pointer<VtkFlutterSession>> out_session,
    ffi.Pointer<VtkFlutterStatus> status,
  ) {
    return _vtk_flutter_session_create(out_session, status);
  }

  late final _vtk_flutter_session_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<ffi.Pointer<VtkFlutterSession>>,
            ffi.Pointer<VtkFlutterStatus>,
          )
        >
      >('vtk_flutter_session_create');
  late final _vtk_flutter_session_create = _vtk_flutter_session_createPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Pointer<VtkFlutterSession>>,
          ffi.Pointer<VtkFlutterStatus>,
        )
      >();

  void vtk_flutter_session_destroy(ffi.Pointer<VtkFlutterSession> session) {
    return _vtk_flutter_session_destroy(session);
  }

  late final _vtk_flutter_session_destroyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VtkFlutterSession>)>
      >('vtk_flutter_session_destroy');
  late final _vtk_flutter_session_destroy = _vtk_flutter_session_destroyPtr
      .asFunction<void Function(ffi.Pointer<VtkFlutterSession>)>();

  int vtk_flutter_validate_volume(
    ffi.Pointer<VtkFlutterVolume> volume,
    ffi.Pointer<VtkFlutterStatus> status,
  ) {
    return _vtk_flutter_validate_volume(volume, status);
  }

  late final _vtk_flutter_validate_volumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VtkFlutterVolume>,
            ffi.Pointer<VtkFlutterStatus>,
          )
        >
      >('vtk_flutter_validate_volume');
  late final _vtk_flutter_validate_volume = _vtk_flutter_validate_volumePtr
      .asFunction<
        int Function(
          ffi.Pointer<VtkFlutterVolume>,
          ffi.Pointer<VtkFlutterStatus>,
        )
      >();

  int vtk_flutter_session_set_volume(
    ffi.Pointer<VtkFlutterSession> session,
    ffi.Pointer<VtkFlutterVolume> volume,
    ffi.Pointer<VtkFlutterStatus> status,
  ) {
    return _vtk_flutter_session_set_volume(session, volume, status);
  }

  late final _vtk_flutter_session_set_volumePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VtkFlutterSession>,
            ffi.Pointer<VtkFlutterVolume>,
            ffi.Pointer<VtkFlutterStatus>,
          )
        >
      >('vtk_flutter_session_set_volume');
  late final _vtk_flutter_session_set_volume =
      _vtk_flutter_session_set_volumePtr
          .asFunction<
            int Function(
              ffi.Pointer<VtkFlutterSession>,
              ffi.Pointer<VtkFlutterVolume>,
              ffi.Pointer<VtkFlutterStatus>,
            )
          >();

  int vtk_flutter_validate_render_request(
    ffi.Pointer<VtkFlutterRenderRequest> request,
    ffi.Pointer<VtkFlutterStatus> status,
  ) {
    return _vtk_flutter_validate_render_request(request, status);
  }

  late final _vtk_flutter_validate_render_requestPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VtkFlutterRenderRequest>,
            ffi.Pointer<VtkFlutterStatus>,
          )
        >
      >('vtk_flutter_validate_render_request');
  late final _vtk_flutter_validate_render_request =
      _vtk_flutter_validate_render_requestPtr
          .asFunction<
            int Function(
              ffi.Pointer<VtkFlutterRenderRequest>,
              ffi.Pointer<VtkFlutterStatus>,
            )
          >();

  int vtk_flutter_session_render(
    ffi.Pointer<VtkFlutterSession> session,
    ffi.Pointer<VtkFlutterRenderRequest> request,
    ffi.Pointer<VtkFlutterMetrics> metrics,
    ffi.Pointer<VtkFlutterStatus> status,
  ) {
    return _vtk_flutter_session_render(session, request, metrics, status);
  }

  late final _vtk_flutter_session_renderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Pointer<VtkFlutterSession>,
            ffi.Pointer<VtkFlutterRenderRequest>,
            ffi.Pointer<VtkFlutterMetrics>,
            ffi.Pointer<VtkFlutterStatus>,
          )
        >
      >('vtk_flutter_session_render');
  late final _vtk_flutter_session_render = _vtk_flutter_session_renderPtr
      .asFunction<
        int Function(
          ffi.Pointer<VtkFlutterSession>,
          ffi.Pointer<VtkFlutterRenderRequest>,
          ffi.Pointer<VtkFlutterMetrics>,
          ffi.Pointer<VtkFlutterStatus>,
        )
      >();
}

final class VtkFlutterSession extends ffi.Opaque {}

enum VtkFlutterStatusCode {
  VTK_FLUTTER_STATUS_OK(0),
  VTK_FLUTTER_STATUS_INVALID_ARGUMENT(1),
  VTK_FLUTTER_STATUS_INVALID_STATE(2),
  VTK_FLUTTER_STATUS_RENDER_TARGET_UNAVAILABLE(3),
  VTK_FLUTTER_STATUS_INTERNAL_ERROR(4);

  final int value;
  const VtkFlutterStatusCode(this.value);

  static VtkFlutterStatusCode fromValue(int value) => switch (value) {
    0 => VTK_FLUTTER_STATUS_OK,
    1 => VTK_FLUTTER_STATUS_INVALID_ARGUMENT,
    2 => VTK_FLUTTER_STATUS_INVALID_STATE,
    3 => VTK_FLUTTER_STATUS_RENDER_TARGET_UNAVAILABLE,
    4 => VTK_FLUTTER_STATUS_INTERNAL_ERROR,
    _ => throw ArgumentError('Unknown value for VtkFlutterStatusCode: $value'),
  };
}

enum VtkFlutterRenderMode {
  VTK_FLUTTER_RENDER_OBLIQUE_MPR(1),
  VTK_FLUTTER_RENDER_VOLUME_3D(2),
  VTK_FLUTTER_RENDER_VOLUME_LOCATOR(3);

  final int value;
  const VtkFlutterRenderMode(this.value);

  static VtkFlutterRenderMode fromValue(int value) => switch (value) {
    1 => VTK_FLUTTER_RENDER_OBLIQUE_MPR,
    2 => VTK_FLUTTER_RENDER_VOLUME_3D,
    3 => VTK_FLUTTER_RENDER_VOLUME_LOCATOR,
    _ => throw ArgumentError('Unknown value for VtkFlutterRenderMode: $value'),
  };
}

final class VtkFlutterStatus extends ffi.Struct {
  @ffi.Int32()
  external int code;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> message;
}

final class VtkFlutterViewport extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;
}

final class VtkFlutterVolume extends ffi.Struct {
  external ffi.Pointer<ffi.Int16> voxels;

  @ffi.Uint64()
  external int voxel_count;

  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  @ffi.Int32()
  external int depth;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Double> index_to_patient;
}

final class VtkFlutterRenderRequest extends ffi.Struct {
  @ffi.Int32()
  external int mode;

  external VtkFlutterViewport viewport;

  @ffi.Double()
  external double window_center;

  @ffi.Double()
  external double window_width;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> plane_origin;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> plane_normal;

  @ffi.Double()
  external double camera_azimuth_degrees;

  @ffi.Double()
  external double camera_elevation_degrees;

  @ffi.Double()
  external double camera_zoom;
}

final class VtkFlutterMetrics extends ffi.Struct {
  @ffi.Uint64()
  external int volume_bytes;

  @ffi.Uint64()
  external int frame_bytes;

  @ffi.Uint64()
  external int surface_allocation_bytes;

  @ffi.Uint64()
  external int surface_checksum;

  @ffi.Uint64()
  external int surface_changed_pixels;

  @ffi.Uint64()
  external int surface_unique_byte_values;

  @ffi.Uint64()
  external int cpu_checksum;

  @ffi.Uint64()
  external int cpu_changed_pixels;

  @ffi.Uint64()
  external int cpu_unique_byte_values;

  @ffi.Double()
  external double render_ms;

  @ffi.Double()
  external double surface_submit_ms;

  @ffi.Double()
  external double gpu_sync_wait_ms;

  @ffi.Double()
  external double cpu_readback_ms;

  @ffi.Int32()
  external int frame_width;

  @ffi.Int32()
  external int frame_height;

  @ffi.Int32()
  external int patient_to_clip_valid;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Double> patient_to_clip;
}

const int VTK_FLUTTER_ABI_VERSION = 1;

const int VTK_FLUTTER_STATUS_MESSAGE_CAPACITY = 256;
