// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:vtk_flutter/vtk_flutter_core.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Uint32 Function()>()
external int vtk_flutter_abi_version();

@ffi.Native<ffi.Pointer<VtkFlutterPresentationApi> Function()>()
external ffi.Pointer<VtkFlutterPresentationApi>
vtk_flutter_get_presentation_api();

@ffi.Native<ffi.Void Function(ffi.Pointer<VtkFlutterStatus>)>()
external void vtk_flutter_status_clear(ffi.Pointer<VtkFlutterStatus> status);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Pointer<VtkFlutterSession>>,
    ffi.Pointer<VtkFlutterStatus>,
  )
>()
external int vtk_flutter_session_create(
  ffi.Pointer<ffi.Pointer<VtkFlutterSession>> out_session,
  ffi.Pointer<VtkFlutterStatus> status,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<VtkFlutterSession>)>()
external void vtk_flutter_session_destroy(
  ffi.Pointer<VtkFlutterSession> session,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<VtkFlutterSession>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<VtkFlutterObjectHandle>,
    ffi.Pointer<VtkFlutterStatus>,
  )
>()
external int vtk_flutter_object_create(
  ffi.Pointer<VtkFlutterSession> session,
  ffi.Pointer<ffi.Char> class_name,
  ffi.Pointer<VtkFlutterObjectHandle> out_object,
  ffi.Pointer<VtkFlutterStatus> status,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<VtkFlutterSession>,
    VtkFlutterObjectHandle,
    ffi.Pointer<VtkFlutterStatus>,
  )
>()
external int vtk_flutter_object_destroy(
  ffi.Pointer<VtkFlutterSession> session,
  int object,
  ffi.Pointer<VtkFlutterStatus> status,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<VtkFlutterSession>,
    VtkFlutterObjectHandle,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<VtkFlutterStatus>,
  )
>()
external int vtk_flutter_object_invoke(
  ffi.Pointer<VtkFlutterSession> session,
  int object,
  ffi.Pointer<ffi.Char> method_name,
  ffi.Pointer<ffi.Char> arguments_json,
  ffi.Pointer<ffi.Pointer<ffi.Char>> result_json,
  ffi.Pointer<VtkFlutterStatus> status,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void vtk_flutter_string_free(ffi.Pointer<ffi.Char> value);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<VtkFlutterSession>,
    ffi.Pointer<VtkFlutterImageData>,
    ffi.Pointer<VtkFlutterObjectHandle>,
    ffi.Pointer<VtkFlutterStatus>,
  )
>()
external int vtk_flutter_image_data_create(
  ffi.Pointer<VtkFlutterSession> session,
  ffi.Pointer<VtkFlutterImageData> image,
  ffi.Pointer<VtkFlutterObjectHandle> out_object,
  ffi.Pointer<VtkFlutterStatus> status,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<VtkFlutterSession>,
    VtkFlutterObjectHandle,
    ffi.Pointer<VtkFlutterViewport>,
    ffi.Pointer<VtkFlutterFrameMetrics>,
    ffi.Pointer<VtkFlutterStatus>,
  )
>()
external int vtk_flutter_session_render(
  ffi.Pointer<VtkFlutterSession> session,
  int renderer,
  ffi.Pointer<VtkFlutterViewport> viewport,
  ffi.Pointer<VtkFlutterFrameMetrics> metrics,
  ffi.Pointer<VtkFlutterStatus> status,
);

final class VtkFlutterSession extends ffi.Opaque {}

final class VtkFlutterTextureTarget extends ffi.Opaque {}

typedef VtkFlutterObjectHandle = ffi.Uint32;
typedef DartVtkFlutterObjectHandle = int;

enum VtkFlutterStatusCode {
  VTK_FLUTTER_STATUS_OK(0),
  VTK_FLUTTER_STATUS_INVALID_ARGUMENT(1),
  VTK_FLUTTER_STATUS_INVALID_STATE(2),
  VTK_FLUTTER_STATUS_NOT_SUPPORTED(3),
  VTK_FLUTTER_STATUS_RENDER_TARGET_UNAVAILABLE(4),
  VTK_FLUTTER_STATUS_INTERNAL_ERROR(5);

  final int value;
  const VtkFlutterStatusCode(this.value);

  static VtkFlutterStatusCode fromValue(int value) => switch (value) {
    0 => VTK_FLUTTER_STATUS_OK,
    1 => VTK_FLUTTER_STATUS_INVALID_ARGUMENT,
    2 => VTK_FLUTTER_STATUS_INVALID_STATE,
    3 => VTK_FLUTTER_STATUS_NOT_SUPPORTED,
    4 => VTK_FLUTTER_STATUS_RENDER_TARGET_UNAVAILABLE,
    5 => VTK_FLUTTER_STATUS_INTERNAL_ERROR,
    _ => throw ArgumentError('Unknown value for VtkFlutterStatusCode: $value'),
  };
}

enum VtkFlutterScalarType {
  VTK_FLUTTER_SCALAR_UINT8(1),
  VTK_FLUTTER_SCALAR_INT8(2),
  VTK_FLUTTER_SCALAR_UINT16(3),
  VTK_FLUTTER_SCALAR_INT16(4),
  VTK_FLUTTER_SCALAR_UINT32(5),
  VTK_FLUTTER_SCALAR_INT32(6),
  VTK_FLUTTER_SCALAR_FLOAT32(7),
  VTK_FLUTTER_SCALAR_FLOAT64(8);

  final int value;
  const VtkFlutterScalarType(this.value);

  static VtkFlutterScalarType fromValue(int value) => switch (value) {
    1 => VTK_FLUTTER_SCALAR_UINT8,
    2 => VTK_FLUTTER_SCALAR_INT8,
    3 => VTK_FLUTTER_SCALAR_UINT16,
    4 => VTK_FLUTTER_SCALAR_INT16,
    5 => VTK_FLUTTER_SCALAR_UINT32,
    6 => VTK_FLUTTER_SCALAR_INT32,
    7 => VTK_FLUTTER_SCALAR_FLOAT32,
    8 => VTK_FLUTTER_SCALAR_FLOAT64,
    _ => throw ArgumentError('Unknown value for VtkFlutterScalarType: $value'),
  };
}

enum VtkFlutterPixelFormat {
  VTK_FLUTTER_PIXEL_FORMAT_RGBA8888(1),
  VTK_FLUTTER_PIXEL_FORMAT_BGRA8888(2);

  final int value;
  const VtkFlutterPixelFormat(this.value);

  static VtkFlutterPixelFormat fromValue(int value) => switch (value) {
    1 => VTK_FLUTTER_PIXEL_FORMAT_RGBA8888,
    2 => VTK_FLUTTER_PIXEL_FORMAT_BGRA8888,
    _ => throw ArgumentError('Unknown value for VtkFlutterPixelFormat: $value'),
  };
}

final class VtkFlutterStatus extends ffi.Struct {
  @ffi.Int32()
  external int code;

  @ffi.Array.multi([512])
  external ffi.Array<ffi.Char> message;
}

final class VtkFlutterViewport extends ffi.Struct {
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;
}

final class VtkFlutterImageData extends ffi.Struct {
  external ffi.Pointer<ffi.Void> values;

  @ffi.Uint64()
  external int value_count;

  @ffi.Uint64()
  external int byte_count;

  @ffi.Int32()
  external int scalar_type;

  @ffi.Int32()
  external int component_count;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Int32> dimensions;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> origin;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.Double> spacing;

  @ffi.Array.multi([9])
  external ffi.Array<ffi.Double> direction;
}

final class VtkFlutterFrameMetrics extends ffi.Struct {
  @ffi.Uint64()
  external int frame_bytes;

  @ffi.Uint64()
  external int surface_allocation_bytes;

  @ffi.Double()
  external double render_ms;

  @ffi.Double()
  external double surface_submit_ms;

  @ffi.Double()
  external double gpu_sync_wait_ms;

  @ffi.Double()
  external double cpu_readback_ms;

  @ffi.Int32()
  external int frame_width;

  @ffi.Int32()
  external int frame_height;

  @ffi.Int32()
  external int world_to_clip_valid;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Double> world_to_clip;
}

final class VtkFlutterCpuFrame extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int version;

  external ffi.Pointer<ffi.Uint8> pixels;

  @ffi.Uint64()
  external int capacity_bytes;

  @ffi.Uint64()
  external int row_bytes;

  @ffi.Int32()
  external int pixel_format;
}

typedef VtkFlutterBeginFrameCallbackFunction =
    ffi.Int32 Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<VtkFlutterViewport> viewport,
      ffi.Pointer<VtkFlutterCpuFrame> frame,
      ffi.Pointer<VtkFlutterStatus> status,
    );
typedef DartVtkFlutterBeginFrameCallbackFunction =
    int Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<VtkFlutterViewport> viewport,
      ffi.Pointer<VtkFlutterCpuFrame> frame,
      ffi.Pointer<VtkFlutterStatus> status,
    );
typedef VtkFlutterBeginFrameCallback =
    ffi.Pointer<ffi.NativeFunction<VtkFlutterBeginFrameCallbackFunction>>;
typedef VtkFlutterEndFrameCallbackFunction =
    ffi.Int32 Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<VtkFlutterFrameMetrics> metrics,
      ffi.Pointer<VtkFlutterStatus> status,
    );
typedef DartVtkFlutterEndFrameCallbackFunction =
    int Function(
      ffi.Pointer<ffi.Void> user_data,
      ffi.Pointer<VtkFlutterFrameMetrics> metrics,
      ffi.Pointer<VtkFlutterStatus> status,
    );
typedef VtkFlutterEndFrameCallback =
    ffi.Pointer<ffi.NativeFunction<VtkFlutterEndFrameCallbackFunction>>;
typedef VtkFlutterCancelFrameCallbackFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> user_data);
typedef DartVtkFlutterCancelFrameCallbackFunction =
    void Function(ffi.Pointer<ffi.Void> user_data);
typedef VtkFlutterCancelFrameCallback =
    ffi.Pointer<ffi.NativeFunction<VtkFlutterCancelFrameCallbackFunction>>;

final class VtkFlutterFrameCallbacks extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int version;

  external ffi.Pointer<ffi.Void> user_data;

  external VtkFlutterBeginFrameCallback begin_frame;

  external VtkFlutterEndFrameCallback end_frame;

  external VtkFlutterCancelFrameCallback cancel_frame;
}

final class VtkFlutterPresentationApi extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int version;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<VtkFlutterStatus> status)>
  >
  status_clear;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<VtkFlutterSession> session,
        ffi.Pointer<VtkFlutterTextureTarget> target,
        ffi.Pointer<VtkFlutterStatus> status,
      )
    >
  >
  session_attach_texture_target;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<VtkFlutterSession> session,
        ffi.Pointer<VtkFlutterTextureTarget> target,
        ffi.Pointer<VtkFlutterStatus> status,
      )
    >
  >
  session_detach_texture_target;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<VtkFlutterFrameCallbacks> callbacks,
        ffi.Pointer<ffi.Pointer<VtkFlutterTextureTarget>> out_target,
        ffi.Pointer<VtkFlutterStatus> status,
      )
    >
  >
  texture_target_create;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int32 Function(
        ffi.Pointer<VtkFlutterTextureTarget> target,
        ffi.Pointer<VtkFlutterStatus> status,
      )
    >
  >
  texture_target_destroy;
}

const int VTK_FLUTTER_ABI_VERSION = 3;

const int VTK_FLUTTER_PRESENTATION_API_VERSION = 1;

const int VTK_FLUTTER_FRAME_CALLBACKS_VERSION = 1;

const int VTK_FLUTTER_CPU_FRAME_VERSION = 1;

const int VTK_FLUTTER_STATUS_MESSAGE_CAPACITY = 512;
