name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

concurrency:
  group: pub-dev-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish package
    if: vars.PUB_DEV_AUTOMATION_ENABLED == 'true'
    permissions:
      contents: read
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
    with:
      environment: pub.dev
